name: Build

on: [ push ]

jobs:
  prepare_dependencies:
    name: Prepare dependencies
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

  test:
    name: Test api-client and composables
    needs: prepare_dependencies
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build api-client
        run: yarn build:api-client

      - name: Test api-client
        run: yarn test:api-client

      - name: Build composables
        run: yarn build:composables

      - name: Test composables
        run: yarn test:composables

      - name: Build theme
        run: yarn build:theme

      - name: Test theme
        run: yarn test:theme

  deploy:
    name: package and deploy the service
    needs: test
    runs-on: [self-hosted, linux]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          push: false
          tags: 795151977897.dkr.ecr.ap-south-1.amazonaws.com/beckn_in_a_box_storefront_ui:${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Cache growth workaround
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Push image to ECR
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 795151977897.dkr.ecr.ap-south-1.amazonaws.com
          docker push 795151977897.dkr.ecr.ap-south-1.amazonaws.com/beckn_in_a_box_storefront_ui:${GITHUB_RUN_NUMBER}
          docker rmi -f 795151977897.dkr.ecr.ap-south-1.amazonaws.com/beckn_in_a_box_storefront_ui:${GITHUB_RUN_NUMBER}
      - name: Deploying to the BIAB servers qa using ansible
        run: |
          cd ansible
          export ANSIBLE_ROLES_PATH=./roles
          echo beckn_in_a_box_storefront_ui_build_no: ${GITHUB_RUN_NUMBER} >> vars/vars.yml
          /home/ubuntu/.local/bin/ansible-playbook playbooks/beckn_services.yml -i inventory/qa.ini --extra-vars "@vars/vars.yml"
